version: '3.8'

services:
#  db:
#    image: postgres
#    container_name: db
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=school-db
#    ports:
#      - "5432:5432"

  school-app:
    image: vincediegane/demo-app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://school-db.c92yqq2aglv7.us-east-1.rds.amazonaws.com:5432/school-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: !!Snlr1992!!
#    depends_on:
#      - db
